---
title: "STA 3180 - Lab 6"
author: "Your Name Here"
date: "2025-04-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Part 1 - NFL Combine 2014 - Physical Characteristics

```{r part1}

nfl.c <- read.csv("http://www.stat.ufl.edu/~winner/data/nfl_combine.csv")
head(nfl.c)
nfl.c <- nfl.c[,3:7]
attach(nfl.c)
head(nfl.c)

n <- nrow(nfl.c)

set.seed(1)
wss1 <- (n-1)*sum(apply(nfl.c[,2:5],2,var)) # sum of squared distances w/ 1 cluster
wss <- numeric(0)

for (i in 2:20) {
  W <- sum(kmeans(nfl.c[,2:5],i)$withinss)
  wss <- c(wss,W)
}
wss <- c(wss1,wss)
wss

plot(1:20,wss,type="l",xlab="number of groups", col="green3",
      ylab="Within group ss",lwd=2,
      main="Within Cluster Sum of Squares by # of Clusters")

nfl.kmeans <- kmeans(nfl.c[,2:5], 5, nstart=25)
nfl.kmeans

color1 <- c("red", "purple", "green3", "grey4", "blue")
par(mfrow=c(2,3))
plot(jitter(Height) ~ ArmLng, col=color1[nfl.kmeans$cluster], pch=16, cex=0.5)
plot(jitter(Height) ~ HandLng, col=color1[nfl.kmeans$cluster], pch=16, cex=0.5)
plot(jitter(Height) ~ Weight, col=color1[nfl.kmeans$cluster], pch=16, cex=0.5)
plot(ArmLng ~ HandLng, col=color1[nfl.kmeans$cluster], pch=16, cex=0.5)
plot(ArmLng ~ Weight, col=color1[nfl.kmeans$cluster], pch=16, cex=0.5)
plot(HandLng ~ Weight, col=color1[nfl.kmeans$cluster], pch=16, cex=0.5)

par(mfrow=c(1,1))

table(nfl.kmeans$cluster, Position) 

z.nfl.c <- scale(nfl.c[,2:5])
z.nfl.c <- data.frame(Position, z.nfl.c)
detach(nfl.c); attach(z.nfl.c)

set.seed(1)
wss1 <- (n-1)*sum(apply(z.nfl.c[,2:5],2,var)) # sum of squared distances w/ 1 cluster
wss <- numeric(0)

for (i in 2:20) {
  W <- sum(kmeans(z.nfl.c[,2:5],i)$withinss)
  wss <- c(wss,W)
}
wss <- c(wss1,wss)
wss

plot(1:20,wss,type="l",xlab="number of groups", col="green3",
      ylab="Within group ss",lwd=2,
      main="Within Cluster Sum of Squares by # of Clusters")

nfl.kmeans.z <- kmeans(z.nfl.c[,2:5], 6, nstart=25)
nfl.kmeans.z

color1 <- c("red", "purple", "green3", "grey4", "blue", "coral")
par(mfrow=c(2,3))
plot(jitter(Height) ~ ArmLng, col=color1[nfl.kmeans.z$cluster], pch=16, cex=0.5)
plot(jitter(Height) ~ HandLng, col=color1[nfl.kmeans.z$cluster], pch=16, cex=0.5)
plot(jitter(Height) ~ Weight, col=color1[nfl.kmeans.z$cluster], pch=16, cex=0.5)
plot(ArmLng ~ HandLng, col=color1[nfl.kmeans.z$cluster], pch=16, cex=0.5)
plot(ArmLng ~ Weight, col=color1[nfl.kmeans.z$cluster], pch=16, cex=0.5)
plot(HandLng ~ Weight, col=color1[nfl.kmeans.z$cluster], pch=16, cex=0.5)

par(mfrow=c(1,1))

table(nfl.kmeans.z$cluster, Position) 

```

## Part 2 - Chemicals in Nigerian Lipstick Products

```{r part2}
nl <- read.csv("http://www.stat.ufl.edu/~winner/sta3180/nigeria_lipstick.csv")
head(nl)

nlm <- nl[,c(1,2,4,6)]
nlm <- data.frame(nl$product,nlm)
attach(nlm)
head(nlm)

ED.12 <- sqrt((nlm$Cr_mn[1] - nlm$Cr_mn[2])^2 + 
              (nlm$Cd_mn[1] - nlm$Cd_mn[2])^2 + 
              (nlm$Pb_mn[1] - nlm$Pb_mn[2])^2)
ED.12

nl.h.c <- hclust(dist(nlm[,-1]),method="complete")   
plot(nl.h.c)
cutree(nl.h.c,h=20) 
abline(h=20, col="red", lwd=3)

nl.h.a <- hclust(dist(nlm[,-1]),method="average")   
plot(nl.h.a)
cutree(nl.h.a,h=15) 
abline(h=15, col="red", lwd=3)

nl.h.s <- hclust(dist(nlm[,-1]),method="single")   
plot(nl.h.s)
cutree(nl.h.s,h=20) 
abline(h=10, col="red", lwd=3)



```

## Part 3 - Chemicals in Brazilian Cocaine Samples

```{r part3}

bc <- read.csv("http://www.stat.ufl.edu/~winner/sta3180/brazil_cocaine.csv")
head(bc)
bc.z <- scale(bc[,-1])
bc.z <- data.frame(bc$sample, bc.z)
attach(bc.z)
head(bc.z)

sample.ID <- 1:length(bc.sample)
state <- ifelse(sample.ID <= 21,1, 2)

bc.h.c <- hclust(dist(bc.z[,-1]),method="complete")   
plot(bc.h.c)
cutree(bc.h.c,h=7) 
abline(h=7, col="red", lwd=3)
table(cutree(bc.h.c,h=7), state)

detach(bc.z)
```